# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-08 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickypanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='api_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='api_secret',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
