# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickypanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='token',
            field=models.CharField(default='token', max_length=100),
            preserve_default=False,
        ),
    ]
