# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickypanel', '0002_auto_20160804_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(default=2014, max_length=100),
            preserve_default=False,
        ),
    ]
