# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickypanel', '0004_auto_20160804_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='api_key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='api_secret',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
